### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by mnpenner** [roperzh/jroff#15]
You have a `package.json` file, but it seems it hasn't been published to npm: https://www.npmjs.com/search?q=jroff

Would make it easier to install if it were 😄 Thanks!

**Comment by roperzh** [comment]
Hey @mnpenner, thanks for checking out jroff! I wrote this a long time ago, mostly as an experiment and therefore I would not advice to use this code 😄.

Having said that, if you're still interested I can publish it tomorrow, no problem at all.

**Comment by mnpenner** [comment]
Hi @roperzh, I tried downloading your script and included into my project manually. It seems your parser is lacking a few features I wanted to so I started writing my own anyway 😄 No need to publish it if you don't want to.

Thanks for posting it regardless, and for your blog post! They've been helpful.

**Comment by roperzh** [comment]
Yay!  That's awesome, could you send me the link to the project when you
finish it? I’d love to take a look at it and include a link to the repo in
the README
